// Maps an airline guide's slug (the part of its href after "/guides/") to the
// matching AirlineLimit.slug in lib/airlines.ts. Most guides follow the pattern
// "{airline-slug}-baggage-allowance", but a handful use a different suffix
// ("-baggage-rules", "-baggage-policy") or drop "-airlines"/"-airways" from the
// slug -- this table is the explicit, verified mapping for all 53 airline guides,
// used by GuideArticle to auto-attach structured baggage-limit data (see
// getAirlineDatasetJsonLd in lib/airlines.ts). Single source of truth: if a new
// airline guide is added, add its mapping here too.
export const AIRLINE_GUIDE_MAP: Record<string, string> = {
  "ryanair-baggage-rules": "ryanair",
  "southwest-baggage-policy": "southwest",
  "lufthansa-baggage-rules": "lufthansa",
  "emirates-baggage-rules": "emirates",
  "british-airways-baggage-allowance": "british-airways",
  "wizz-air-baggage-rules": "wizz-air",
  "qantas-baggage-allowance": "qantas",
  "turkish-airlines-baggage-allowance": "turkish-airlines",
  "icelandair-baggage-allowance": "icelandair",
  "delta-baggage-allowance": "delta",
  "united-airlines-baggage-allowance": "united",
  "air-canada-baggage-allowance": "air-canada",
  "singapore-airlines-baggage-allowance": "singapore-airlines",
  "easyjet-baggage-allowance": "easyjet",
  "american-airlines-baggage-allowance": "american",
  "jetblue-baggage-allowance": "jetblue",
  "alaska-airlines-baggage-allowance": "alaska",
  "air-france-baggage-allowance": "air-france",
  "sas-baggage-allowance": "sas",
  "swiss-baggage-allowance": "swiss",
  "finnair-baggage-allowance": "finnair",
  "klm-baggage-allowance": "klm",
  "qatar-airways-baggage-allowance": "qatar-airways",
  "etihad-airways-baggage-allowance": "etihad",
  "cathay-pacific-baggage-allowance": "cathay-pacific",
  "norwegian-baggage-allowance": "norwegian",
  "aer-lingus-baggage-allowance": "aer-lingus",
  "japan-airlines-baggage-allowance": "japan-airlines",
  "ana-baggage-allowance": "ana",
  "jet2-baggage-allowance": "jet2",
  "westjet-baggage-allowance": "westjet",
  "tap-air-portugal-baggage-allowance": "tap-air-portugal",
  "iberia-baggage-allowance": "iberia",
  "korean-air-baggage-allowance": "korean-air",
  "thai-airways-baggage-allowance": "thai-airways",
  "air-india-baggage-allowance": "air-india",
  "air-new-zealand-baggage-allowance": "air-new-zealand",
  "virgin-australia-baggage-allowance": "virgin-australia",
  "austrian-airlines-baggage-allowance": "austrian",
  "brussels-airlines-baggage-allowance": "brussels-airlines",
  "ita-airways-baggage-allowance": "ita-airways",
  "lot-polish-airlines-baggage-allowance": "lot-polish",
  "aegean-airlines-baggage-allowance": "aegean",
  "vueling-baggage-allowance": "vueling",
  "eurowings-baggage-allowance": "eurowings",
  "eva-air-baggage-allowance": "eva-air",
  "transavia-baggage-allowance": "transavia",
  "airbaltic-baggage-allowance": "airbaltic",
  "pegasus-airlines-baggage-allowance": "pegasus-airlines",
  "wideroe-baggage-allowance": "wideroe",
  "norse-atlantic-airways-baggage-allowance": "norse-atlantic",
  "china-airlines-baggage-allowance": "china-airlines",
  "jetstar-baggage-allowance": "jetstar",
};
