// Carry-on size and weight limits by airline.
// Source: aggregated from published airline cabin-baggage policies, cross-checked against
// Upgraded Points' 2026 carry-on size chart (https://upgradedpoints.com/travel/airlines/carry-on-luggage-size-chart/)
// and individual airline sources for the rest. Dimensions in centimeters (L x W x H), weight in
// kilograms. Always verify against the airline's own site before flying — policies change and can
// vary by fare class or route.

export type AirlineLimit = {
  slug: string;
  name: string;
  region: "North America" | "Europe" | "Middle East" | "Asia-Pacific";
  measurement: "dimensions" | "linear";
  // for "dimensions" airlines
  maxCm?: [number, number, number]; // L x W x H, cm
  // for "linear" airlines (sum of L+W+H)
  maxLinearCm?: number;
  maxWeightKg: number | null; // null = no published cabin-bag weight limit
  weightNote?: string;
  source: string;
};

export const AIRLINES: AirlineLimit[] = [
  {
    slug: "united",
    name: "United Airlines",
    region: "North America",
    measurement: "dimensions",
    maxCm: [56, 35, 23],
    maxWeightKg: null,
    source: "united.com",
  },
  {
    slug: "delta",
    name: "Delta Air Lines",
    region: "North America",
    measurement: "dimensions",
    maxCm: [56, 35, 23],
    maxWeightKg: null,
    weightNote: "No general weight limit, but some codeshare/regional routes vary.",
    source: "delta.com",
  },
  {
    slug: "american",
    name: "American Airlines",
    region: "North America",
    measurement: "dimensions",
    maxCm: [56, 36, 23],
    maxWeightKg: null,
    source: "aa.com",
  },
  {
    slug: "southwest",
    name: "Southwest Airlines",
    region: "North America",
    measurement: "dimensions",
    maxCm: [61, 41, 25],
    maxWeightKg: null,
    source: "southwest.com",
  },
  {
    slug: "jetblue",
    name: "JetBlue Airways",
    region: "North America",
    measurement: "dimensions",
    maxCm: [56, 36, 23],
    maxWeightKg: null,
    source: "jetblue.com",
  },
  {
    slug: "alaska",
    name: "Alaska Airlines",
    region: "North America",
    measurement: "dimensions",
    maxCm: [56, 36, 23],
    maxWeightKg: null,
    source: "alaskaair.com",
  },
  {
    slug: "air-canada",
    name: "Air Canada",
    region: "North America",
    measurement: "dimensions",
    maxCm: [55, 40, 23],
    maxWeightKg: null,
    source: "aircanada.com",
  },
  {
    slug: "westjet",
    name: "WestJet",
    region: "North America",
    measurement: "dimensions",
    maxCm: [56, 36, 23],
    maxWeightKg: null,
    weightNote: "Basic (UltraBasic) fares don't include a cabin bag, only a personal item.",
    source: "westjet.com",
  },
  {
    slug: "british-airways",
    name: "British Airways",
    region: "Europe",
    measurement: "dimensions",
    maxCm: [56, 45, 25],
    maxWeightKg: null,
    weightNote: "No published weight limit, but you must be able to lift it into the locker.",
    source: "britishairways.com",
  },
  {
    slug: "lufthansa",
    name: "Lufthansa",
    region: "Europe",
    measurement: "dimensions",
    maxCm: [55, 40, 23],
    maxWeightKg: 8,
    source: "lufthansa.com",
  },
  {
    slug: "air-france",
    name: "Air France",
    region: "Europe",
    measurement: "dimensions",
    maxCm: [55, 35, 25],
    maxWeightKg: 12,
    weightNote: "Basic Economy includes only a personal item; a full cabin bag must be added separately.",
    source: "airfrance.com",
  },
  {
    slug: "klm",
    name: "KLM",
    region: "Europe",
    measurement: "dimensions",
    maxCm: [55, 35, 25],
    maxWeightKg: 12,
    weightNote: "12 kg is the combined limit for cabin bag + personal item, shared policy with Air France.",
    source: "klm.com",
  },
  {
    slug: "ryanair",
    name: "Ryanair",
    region: "Europe",
    measurement: "dimensions",
    maxCm: [55, 40, 20],
    maxWeightKg: 10,
    weightNote: "10 kg bag requires the paid Priority option; free bag is smaller (40x20x25cm).",
    source: "ryanair.com",
  },
  {
    slug: "easyjet",
    name: "easyJet",
    region: "Europe",
    measurement: "dimensions",
    maxCm: [56, 45, 25],
    maxWeightKg: 15,
    weightNote: "Free \"under-seat\" bag is smaller; this size requires a cabin bag fare/add-on.",
    source: "easyjet.com",
  },
  {
    slug: "norwegian",
    name: "Norwegian",
    region: "Europe",
    measurement: "dimensions",
    maxCm: [55, 40, 23],
    maxWeightKg: 10,
    source: "norwegian.com",
  },
  {
    slug: "sas",
    name: "SAS (Scandinavian Airlines)",
    region: "Europe",
    measurement: "dimensions",
    maxCm: [55, 40, 23],
    maxWeightKg: 8,
    source: "flysas.com",
  },
  {
    slug: "swiss",
    name: "Swiss International Air Lines",
    region: "Europe",
    measurement: "dimensions",
    maxCm: [55, 40, 23],
    maxWeightKg: 8,
    source: "swiss.com",
  },
  {
    slug: "austrian",
    name: "Austrian Airlines",
    region: "Europe",
    measurement: "dimensions",
    maxCm: [55, 40, 23],
    maxWeightKg: 8,
    source: "austrian.com",
  },
  {
    slug: "brussels-airlines",
    name: "Brussels Airlines",
    region: "Europe",
    measurement: "dimensions",
    maxCm: [55, 40, 23],
    maxWeightKg: 8,
    source: "brusselsairlines.com",
  },
  {
    slug: "tap-air-portugal",
    name: "TAP Air Portugal",
    region: "Europe",
    measurement: "dimensions",
    maxCm: [55, 40, 25],
    maxWeightKg: 10,
    source: "flytap.com",
  },
  {
    slug: "iberia",
    name: "Iberia",
    region: "Europe",
    measurement: "dimensions",
    maxCm: [56, 40, 25],
    maxWeightKg: 10,
    weightNote: "Business class gets 14 kg on short/medium-haul routes.",
    source: "iberia.com",
  },
  {
    slug: "ita-airways",
    name: "ITA Airways",
    region: "Europe",
    measurement: "dimensions",
    maxCm: [55, 40, 23],
    maxWeightKg: 8,
    source: "ita-airways.com",
  },
  {
    slug: "lot-polish",
    name: "LOT Polish Airlines",
    region: "Europe",
    measurement: "dimensions",
    maxCm: [55, 40, 23],
    maxWeightKg: 8,
    weightNote: "Plus a free personal item up to 40x35x12cm.",
    source: "lot.com",
  },
  {
    slug: "turkish-airlines",
    name: "Turkish Airlines",
    region: "Europe",
    measurement: "dimensions",
    maxCm: [55, 40, 23],
    maxWeightKg: 8,
    source: "turkishairlines.com",
  },
  {
    slug: "aegean",
    name: "Aegean Airlines",
    region: "Europe",
    measurement: "dimensions",
    maxCm: [56, 45, 25],
    maxWeightKg: 8,
    weightNote: "Economy Light fares must choose either the cabin bag or the personal item, not both.",
    source: "aegeanair.com",
  },
  {
    slug: "aer-lingus",
    name: "Aer Lingus",
    region: "Europe",
    measurement: "dimensions",
    maxCm: [55, 40, 24],
    maxWeightKg: 10,
    source: "aerlingus.com",
  },
  {
    slug: "wizz-air",
    name: "Wizz Air",
    region: "Europe",
    measurement: "dimensions",
    maxCm: [55, 40, 23],
    maxWeightKg: 10,
    weightNote: "10 kg bag requires a paid fare upgrade; the free allowance is a smaller 40x30x20cm bag.",
    source: "wizzair.com",
  },
  {
    slug: "vueling",
    name: "Vueling",
    region: "Europe",
    measurement: "dimensions",
    maxCm: [55, 40, 20],
    maxWeightKg: 10,
    weightNote: "Basic fares include only a small personal item; this size and weight is a paid add-on.",
    source: "vueling.com",
  },
  {
    slug: "eurowings",
    name: "Eurowings",
    region: "Europe",
    measurement: "dimensions",
    maxCm: [55, 40, 23],
    maxWeightKg: 8,
    weightNote: "BASIC fares include only the free personal item (40x30x25cm); this size is a paid add-on.",
    source: "eurowings.com",
  },
  {
    slug: "transavia",
    name: "Transavia",
    region: "Europe",
    measurement: "dimensions",
    maxCm: [55, 40, 25],
    maxWeightKg: 10,
    weightNote: "Free fares include only a personal item (40x30x20cm); this size is a paid cabin-bag option.",
    source: "transavia.com",
  },
  {
    slug: "jet2",
    name: "Jet2",
    region: "Europe",
    measurement: "dimensions",
    maxCm: [56, 45, 25],
    maxWeightKg: 10,
    weightNote: "Free on every fare, alongside a separate personal item.",
    source: "jet2.com",
  },
  {
    slug: "airbaltic",
    name: "airBaltic",
    region: "Europe",
    measurement: "dimensions",
    maxCm: [55, 40, 23],
    maxWeightKg: 8,
    weightNote: "8 kg is the combined weight of the cabin bag and personal item together.",
    source: "airbaltic.com",
  },
  {
    slug: "pegasus-airlines",
    name: "Pegasus Airlines",
    region: "Europe",
    measurement: "dimensions",
    maxCm: [55, 40, 20],
    maxWeightKg: 8,
    weightNote: "Light fares on international routes are restricted to a small personal item only (40x30x15cm, 3kg).",
    source: "flypgs.com",
  },
  {
    slug: "wideroe",
    name: "Widerøe",
    region: "Europe",
    measurement: "dimensions",
    maxCm: [55, 40, 20],
    maxWeightKg: 8,
    weightNote: "8 kg is the combined weight of the cabin bag and personal item together.",
    source: "wideroe.no",
  },
  {
    slug: "norse-atlantic",
    name: "Norse Atlantic Airways",
    region: "Europe",
    measurement: "dimensions",
    maxCm: [56, 45, 25],
    maxWeightKg: 10,
    weightNote: "Premium cabin passengers get 15 kg.",
    source: "flynorse.com",
  },
  {
    slug: "finnair",
    name: "Finnair",
    region: "Europe",
    measurement: "dimensions",
    maxCm: [55, 40, 23],
    maxWeightKg: 8,
    weightNote: "Economy Superlight fares don't include a cabin bag at all, only a personal item.",
    source: "finnair.com",
  },
  {
    slug: "icelandair",
    name: "Icelandair",
    region: "Europe",
    measurement: "dimensions",
    maxCm: [55, 40, 20],
    maxWeightKg: 10,
    weightNote: "Domestic and Greenland routes are limited to 6 kg.",
    source: "icelandair.com",
  },
  {
    slug: "emirates",
    name: "Emirates",
    region: "Middle East",
    measurement: "dimensions",
    maxCm: [55, 38, 22],
    maxWeightKg: 7,
    weightNote: "Business/First allowance is higher (9 kg) — check your fare class.",
    source: "emirates.com",
  },
  {
    slug: "qatar-airways",
    name: "Qatar Airways",
    region: "Middle East",
    measurement: "dimensions",
    maxCm: [50, 37, 25],
    maxWeightKg: 7,
    source: "qatarairways.com",
  },
  {
    slug: "etihad",
    name: "Etihad Airways",
    region: "Middle East",
    measurement: "dimensions",
    maxCm: [56, 36, 23],
    maxWeightKg: 7,
    weightNote: "Business/First allowance is 12 kg total.",
    source: "etihad.com",
  },
  {
    slug: "singapore-airlines",
    name: "Singapore Airlines",
    region: "Asia-Pacific",
    measurement: "linear",
    maxLinearCm: 115,
    maxWeightKg: 7,
    weightNote: "Measured as total linear dimensions (L+W+H), not per-side limits.",
    source: "singaporeair.com",
  },
  {
    slug: "thai-airways",
    name: "Thai Airways",
    region: "Asia-Pacific",
    measurement: "dimensions",
    maxCm: [56, 45, 25],
    maxWeightKg: 7,
    source: "thaiairways.com",
  },
  {
    slug: "cathay-pacific",
    name: "Cathay Pacific",
    region: "Asia-Pacific",
    measurement: "dimensions",
    maxCm: [56, 36, 23],
    maxWeightKg: 7,
    weightNote: "Business gets 10 kg, First gets 15 kg.",
    source: "cathaypacific.com",
  },
  {
    slug: "japan-airlines",
    name: "Japan Airlines",
    region: "Asia-Pacific",
    measurement: "dimensions",
    maxCm: [55, 40, 25],
    maxWeightKg: 10,
    source: "jal.com",
  },
  {
    slug: "ana",
    name: "ANA (All Nippon Airways)",
    region: "Asia-Pacific",
    measurement: "dimensions",
    maxCm: [55, 40, 25],
    maxWeightKg: 10,
    source: "ana.co.jp",
  },
  {
    slug: "korean-air",
    name: "Korean Air",
    region: "Asia-Pacific",
    measurement: "dimensions",
    maxCm: [55, 40, 20],
    maxWeightKg: 10,
    weightNote: "First/Prestige gets 18 kg.",
    source: "koreanair.com",
  },
  {
    slug: "china-airlines",
    name: "China Airlines",
    region: "Asia-Pacific",
    measurement: "dimensions",
    maxCm: [56, 36, 23],
    maxWeightKg: 7,
    source: "china-airlines.com",
  },
  {
    slug: "eva-air",
    name: "EVA Air",
    region: "Asia-Pacific",
    measurement: "dimensions",
    maxCm: [56, 36, 23],
    maxWeightKg: 7,
    source: "evaair.com",
  },
  {
    slug: "air-india",
    name: "Air India",
    region: "Asia-Pacific",
    measurement: "dimensions",
    maxCm: [55, 40, 20],
    maxWeightKg: 7,
    weightNote: "Business/First gets 10 kg.",
    source: "airindia.com",
  },
  {
    slug: "qantas",
    name: "Qantas",
    region: "Asia-Pacific",
    measurement: "dimensions",
    maxCm: [56, 36, 23],
    maxWeightKg: 7,
    weightNote: "Domestic and international long-haul often allow two pieces (7 kg each, 14 kg total) — check your fare.",
    source: "qantas.com",
  },
  {
    slug: "virgin-australia",
    name: "Virgin Australia",
    region: "Asia-Pacific",
    measurement: "dimensions",
    maxCm: [56, 36, 23],
    maxWeightKg: 8,
    weightNote: "Limit tightened to 8 kg from 2 February 2026, plus a small personal item.",
    source: "virginaustralia.com",
  },
  {
    slug: "air-new-zealand",
    name: "Air New Zealand",
    region: "Asia-Pacific",
    measurement: "dimensions",
    maxCm: [55, 40, 23],
    maxWeightKg: 7,
    weightNote: "Premium Economy/Business gets 14 kg total.",
    source: "airnewzealand.com",
  },
  {
    slug: "jetstar",
    name: "Jetstar Airways",
    region: "Asia-Pacific",
    measurement: "dimensions",
    maxCm: [56, 36, 23],
    maxWeightKg: 7,
    weightNote: "7 kg is the combined weight of the main bag and small item together.",
    source: "jetstar.com",
  },
];

export type CheckResult = {
  airline: AirlineLimit;
  dimensionsOk: boolean;
  weightOk: boolean | null; // null = no weight limit to check against
};

export function checkBag(
  lengthCm: number,
  widthCm: number,
  heightCm: number,
  weightKg: number | null
): CheckResult[] {
  const bagSorted = [lengthCm, widthCm, heightCm].sort((a, b) => b - a);
  const bagLinear = lengthCm + widthCm + heightCm;

  return AIRLINES.map((airline) => {
    let dimensionsOk: boolean;
    if (airline.measurement === "linear" && airline.maxLinearCm) {
      dimensionsOk = bagLinear <= airline.maxLinearCm;
    } else if (airline.maxCm) {
      const limitSorted = [...airline.maxCm].sort((a, b) => b - a);
      dimensionsOk = bagSorted.every((d, i) => d <= limitSorted[i]);
    } else {
      dimensionsOk = true;
    }

    const weightOk =
      airline.maxWeightKg === null || weightKg === null
        ? null
        : weightKg <= airline.maxWeightKg;

    return { airline, dimensionsOk, weightOk };
  });
}
