// Guide index — shared by the homepage, the guides listing and the footer.
// Photos: Unsplash (free licence), a matching three-part series by one photographer.

export type GuideChip = "sun" | "sky" | "coral";

export type GuideMeta = {
  href: string;
  title: string;
  blurb: string;
  chip: string;
  chipColor: GuideChip;
  img: string;
  updated: string;
};

export const GUIDES: GuideMeta[] = [
  {
    href: "/guides/best-carry-on-luggage",
    title: "Best carry-on luggage",
    blurb: "Size, weight, shell, wheels — the four decisions that matter, in order.",
    chip: "Carry-on",
    chipColor: "sun",
    img: "https://images.unsplash.com/photo-1670888616036-ed6e723c07e6?q=80&w=1000&auto=format&fit=crop",
    updated: "September 2026",
  },
  {
    href: "/guides/best-checked-luggage",
    title: "Best checked luggage",
    blurb: "Durability, expansion and how airline weight limits really work.",
    chip: "Checked",
    chipColor: "sky",
    img: "https://images.unsplash.com/photo-1670888664952-efff442ec0d2?q=80&w=1000&auto=format&fit=crop",
    updated: "September 2026",
  },
  {
    href: "/guides/samsonite-vs-delsey",
    title: "Samsonite vs Delsey",
    blurb: "Two giants compared on materials, warranty and real-world wear.",
    chip: "Brand duel",
    chipColor: "coral",
    img: "https://images.unsplash.com/photo-1670888616427-764112453941?q=80&w=1000&auto=format&fit=crop",
    updated: "September 2026",
  },
  {
    href: "/guides/ryanair-baggage-rules",
    title: "Ryanair baggage rules, explained",
    blurb: "Free personal item, paid Priority bag, and where the 10 kg limit gets enforced.",
    chip: "Airline guide",
    chipColor: "sky",
    img: "https://images.unsplash.com/photo-1673505379276-fd25416b6e55?q=80&w=1000&auto=format&fit=crop",
    updated: "September 2026",
  },
  {
    href: "/guides/southwest-baggage-policy",
    title: "Southwest's baggage policy has changed",
    blurb: "The two-free-bags era is over for most flyers — here's who still gets them free.",
    chip: "Airline guide",
    chipColor: "coral",
    img: "https://images.unsplash.com/photo-1702411739431-0b6874405792?q=80&w=1000&auto=format&fit=crop",
    updated: "September 2026",
  },
  {
    href: "/guides/best-lightweight-carry-on-luggage",
    title: "Best lightweight carry-on luggage",
    blurb: "The lightest bags we could verify, ranked by actual empty weight — not marketing copy.",
    chip: "Buying guide",
    chipColor: "sun",
    img: "https://images.unsplash.com/photo-1673505705824-e6abaa279c97?q=80&w=1000&auto=format&fit=crop",
    updated: "September 2026",
  },
  {
    href: "/guides/avoid-checked-baggage-fees",
    title: "How to avoid checked baggage fees",
    blurb: "Credit cards, elite status and packing choices, ranked by how much they actually save.",
    chip: "Money-saving",
    chipColor: "sky",
    img: "https://images.unsplash.com/photo-1762965119363-af950b523dca?q=80&w=1000&auto=format&fit=crop",
    updated: "September 2026",
  },
  {
    href: "/guides/lufthansa-baggage-rules",
    title: "Lufthansa baggage rules, by fare class",
    blurb: "The cabin bag is fixed at 8 kg — the checked bag depends entirely on your fare.",
    chip: "Airline guide",
    chipColor: "coral",
    img: "https://images.unsplash.com/photo-1706967930742-9d6c5238e7e4?q=80&w=1000&auto=format&fit=crop",
    updated: "September 2026",
  },
  {
    href: "/guides/emirates-baggage-rules",
    title: "Emirates baggage rules, explained",
    blurb: "Piece-based or weight-based checked baggage — it depends entirely on your route.",
    chip: "Airline guide",
    chipColor: "sky",
    img: "https://images.unsplash.com/photo-1591632175697-f07e2d75dacb?q=80&w=1000&auto=format&fit=crop",
    updated: "September 2026",
  },
  {
    href: "/guides/carry-on-vs-personal-item",
    title: "Carry-on vs personal item, what's the difference",
    blurb: "We compared the free personal-item size across our own dataset — it varies by over 50%.",
    chip: "Explainer",
    chipColor: "sun",
    img: "https://images.unsplash.com/photo-1504150558240-0b4fd8946624?q=80&w=1000&auto=format&fit=crop",
    updated: "September 2026",
  },
  {
    href: "/guides/best-luggage-for-business-travel",
    title: "Best luggage for business travel",
    blurb: "Laptop access, garment protection and a weight budget that survives Lufthansa or Emirates.",
    chip: "Buying guide",
    chipColor: "coral",
    img: "https://images.unsplash.com/photo-1574202141112-c3a90e1a3ce2?q=80&w=1000&auto=format&fit=crop",
    updated: "September 2026",
  },
  {
    href: "/guides/british-airways-baggage-allowance",
    title: "British Airways baggage allowance, by fare",
    blurb: "Checked bags scale from zero to three depending on cabin and fare — here's the full breakdown.",
    chip: "Airline guide",
    chipColor: "sky",
    img: "https://images.unsplash.com/photo-1698584109673-12d97bc70d08?q=80&w=1000&auto=format&fit=crop",
    updated: "September 2026",
  },
  {
    href: "/guides/what-not-to-pack-in-carry-on",
    title: "What not to pack in your carry-on",
    blurb: "Liquids, sharp objects, sporting goods, and the one item that must go in the cabin, not checked.",
    chip: "Explainer",
    chipColor: "coral",
    img: "https://images.unsplash.com/photo-1673505705715-8deb093d39e8?q=80&w=1000&auto=format&fit=crop",
    updated: "September 2026",
  },
  {
    href: "/guides/best-luggage-for-family-travel",
    title: "Best luggage for family travel",
    blurb: "Hard-shell durability, wheel quality, and why a 3-piece set beats one bag per traveler.",
    chip: "Buying guide",
    chipColor: "sun",
    img: "https://images.unsplash.com/photo-1673505705677-93516a00ca06?q=80&w=1000&auto=format&fit=crop",
    updated: "September 2026",
  },
  {
    href: "/guides/wizz-air-baggage-rules",
    title: "Wizz Air baggage rules, explained",
    blurb: "One free personal item, a paid Priority cabin bag, and four checked-bag weight tiers.",
    chip: "Airline guide",
    chipColor: "sky",
    img: "https://images.unsplash.com/photo-1602191595949-1b1e5fb5634a?q=80&w=1000&auto=format&fit=crop",
    updated: "September 2026",
  },
  {
    href: "/guides/qantas-baggage-allowance",
    title: "Qantas baggage allowance, explained",
    blurb: "Weight-based on some routes, piece-based on others -- here's which applies to you.",
    chip: "Airline guide",
    chipColor: "coral",
    img: "https://images.unsplash.com/photo-1503365194569-df4e1d04cec1?q=80&w=1000&auto=format&fit=crop",
    updated: "September 2026",
  },
  {
    href: "/guides/turkish-airlines-baggage-allowance",
    title: "Turkish Airlines baggage allowance",
    blurb: "Your checked allowance depends on the KG or PC concept -- and it's printed on your ticket.",
    chip: "Airline guide",
    chipColor: "sun",
    img: "https://images.unsplash.com/photo-1527007622069-3a0241e1cd8c?q=80&w=1000&auto=format&fit=crop",
    updated: "September 2026",
  },
  {
    href: "/guides/icelandair-baggage-allowance",
    title: "Icelandair baggage allowance",
    blurb: "The cheapest fare includes zero checked bags -- and stopover fees apply per leg, not per trip.",
    chip: "Airline guide",
    chipColor: "sky",
    img: "https://images.unsplash.com/photo-1530521954074-e64f6810b32d?q=80&w=1000&auto=format&fit=crop",
    updated: "September 2026",
  },
  {
    href: "/guides/delta-baggage-allowance",
    title: "Delta baggage allowance and fees",
    blurb: "No cabin-bag weight limit, but checked fees swing hard between Basic Economy and Main Cabin.",
    chip: "Airline guide",
    chipColor: "coral",
    img: "https://images.unsplash.com/photo-1572358707000-39729872feba?q=80&w=1000&auto=format&fit=crop",
    updated: "September 2026",
  },
  {
    href: "/guides/united-airlines-baggage-allowance",
    title: "United Airlines baggage allowance",
    blurb: "Fare class sets the checked-bag fee -- but elite status and some credit cards can waive it.",
    chip: "Airline guide",
    chipColor: "sun",
    img: "https://images.unsplash.com/photo-1714235058886-a0b38ad5066c?q=80&w=1000&auto=format&fit=crop",
    updated: "September 2026",
  },
  {
    href: "/guides/air-canada-baggage-allowance",
    title: "Air Canada baggage allowance",
    blurb: "The cheapest fare shrinks your carry-on too, not just checked bags, on Canada-U.S. routes.",
    chip: "Airline guide",
    chipColor: "sky",
    img: "https://images.unsplash.com/photo-1714235058817-af16a662fe1d?q=80&w=1000&auto=format&fit=crop",
    updated: "September 2026",
  },
  {
    href: "/guides/singapore-airlines-baggage-allowance",
    title: "Singapore Airlines baggage allowance",
    blurb: "Even the cheapest fare includes a checked bag -- rare among full-service carriers today.",
    chip: "Airline guide",
    chipColor: "coral",
    img: "https://images.unsplash.com/photo-1564209906116-fb6887675069?q=80&w=1000&auto=format&fit=crop",
    updated: "September 2026",
  },
  {
    href: "/guides/easyjet-baggage-allowance",
    title: "easyJet baggage allowance",
    blurb: "The free bag is smaller than you think, and a gate mistake costs a flat GBP 50.",
    chip: "Airline guide",
    chipColor: "sun",
    img: "https://images.unsplash.com/photo-1569512850669-7baa648e82d8?q=80&w=1000&auto=format&fit=crop",
    updated: "September 2026",
  },
  {
    href: "/guides/american-airlines-baggage-allowance",
    title: "American Airlines baggage allowance",
    blurb: "Basic Economy still includes a full carry-on -- the one thing several rivals don't offer.",
    chip: "Airline guide",
    chipColor: "sky",
    img: "https://images.unsplash.com/photo-1603792835233-f4f7c2497d4f?q=80&w=1000&auto=format&fit=crop",
    updated: "September 2026",
  },
  {
    href: "/guides/jetblue-baggage-allowance",
    title: "JetBlue baggage allowance",
    blurb: "The same Blue Basic fare charges for a first bag at home and gives one away free to Europe.",
    chip: "Airline guide",
    chipColor: "coral",
    img: "https://images.unsplash.com/photo-1663030083159-5a58ca80c4ef?q=80&w=1000&auto=format&fit=crop",
    updated: "September 2026",
  },
  {
    href: "/guides/alaska-airlines-baggage-allowance",
    title: "Alaska Airlines baggage allowance",
    blurb: "Same price online or at the airport, plus a 20-minute bag guarantee most US carriers don't match.",
    chip: "Airline guide",
    chipColor: "sun",
    img: "https://images.unsplash.com/photo-1773228972271-41d02886869b?q=80&w=1000&auto=format&fit=crop",
    updated: "September 2026",
  },
  {
    href: "/guides/air-france-baggage-allowance",
    title: "Air France baggage allowance",
    blurb: "Economy Light means zero checked bags -- but status bonuses carry over from sister airline KLM.",
    chip: "Airline guide",
    chipColor: "sky",
    img: "https://images.unsplash.com/photo-1708403120467-1715bb6840df?q=80&w=1000&auto=format&fit=crop",
    updated: "September 2026",
  },
  {
    href: "/guides/sas-baggage-allowance",
    title: "SAS baggage allowance",
    blurb: "Economy Light means something different depending on where you're flying -- and a 2026 update now gives Silver members a free bag.",
    chip: "Airline guide",
    chipColor: "coral",
    img: "https://images.unsplash.com/photo-1549894595-4698795b38ee?q=80&w=1000&auto=format&fit=crop",
    updated: "September 2026",
  },
  {
    href: "/guides/swiss-baggage-allowance",
    title: "Swiss baggage allowance",
    blurb: "Light means hand-luggage-only everywhere Swiss flies, and the 32kg weight cap has no pay-your-way-out option.",
    chip: "Airline guide",
    chipColor: "sun",
    img: "https://images.unsplash.com/photo-1654686473683-79cef3d57db6?q=80&w=1000&auto=format&fit=crop",
    updated: "September 2026",
  },
  {
    href: "/guides/finnair-baggage-allowance",
    title: "Finnair baggage allowance",
    blurb: "How many bags you get depends more on the route than the fare -- Asia flights can beat Europe by two full bags.",
    chip: "Airline guide",
    chipColor: "sky",
    img: "https://images.unsplash.com/photo-1558413203-528a11565bf4?q=80&w=1000&auto=format&fit=crop",
    updated: "September 2026",
  },
  {
    href: "/guides/klm-baggage-allowance",
    title: "KLM baggage allowance",
    blurb: "Despite the name, Economy Basic doesn't even include a full-size carry-on -- just an under-seat bag.",
    chip: "Airline guide",
    chipColor: "coral",
    img: "https://images.unsplash.com/photo-1629308993023-bb7ca078abdc?q=80&w=1000&auto=format&fit=crop",
    updated: "September 2026",
  },
];

export const CHIP_BG: Record<GuideChip, string> = {
  sun: "bg-sun text-ink",
  sky: "bg-sky text-cream",
  coral: "bg-coral text-ink",
};
