// Guide index — shared by the homepage, the guides listing and the footer.
// Photos: Unsplash (free licence), a matching three-part series by one photographer.

export type GuideChip = "sun" | "sky" | "coral";

export type GuideMeta = {
  href: string;
  title: string;
  blurb: string;
  chip: string;
  chipColor: GuideChip;
  img: string;
  updated: string;
};

export const GUIDES: GuideMeta[] = [
  {
    href: "/guides/best-carry-on-luggage",
    title: "Best carry-on luggage",
    blurb: "Size, weight, shell, wheels — the four decisions that matter, in order.",
    chip: "Carry-on",
    chipColor: "sun",
    img: "/images/guides/best-carry-on-luggage.jpg",
    updated: "September 2026",
  },
  {
    href: "/guides/best-checked-luggage",
    title: "Best checked luggage",
    blurb: "Durability, expansion and how airline weight limits really work.",
    chip: "Checked",
    chipColor: "sky",
    img: "/images/guides/best-checked-luggage.jpg",
    updated: "September 2026",
  },
  {
    href: "/guides/samsonite-vs-delsey",
    title: "Samsonite vs Delsey",
    blurb: "Two giants compared on materials, warranty and real-world wear.",
    chip: "Brand duel",
    chipColor: "coral",
    img: "/images/guides/samsonite-vs-delsey.jpg",
    updated: "September 2026",
  },
  {
    href: "/guides/ryanair-baggage-rules",
    title: "Ryanair baggage rules, explained",
    blurb: "Free personal item, paid Priority bag, and where the 10 kg limit gets enforced.",
    chip: "Airline guide",
    chipColor: "sky",
    img: "/images/guides/ryanair-baggage-rules.jpg",
    updated: "September 2026",
  },
  {
    href: "/guides/southwest-baggage-policy",
    title: "Southwest's baggage policy has changed",
    blurb: "The two-free-bags era is over for most flyers — here's who still gets them free.",
    chip: "Airline guide",
    chipColor: "coral",
    img: "/images/guides/southwest-baggage-policy.jpg",
    updated: "September 2026",
  },
  {
    href: "/guides/best-lightweight-carry-on-luggage",
    title: "Best lightweight carry-on luggage",
    blurb: "The lightest bags we could verify, ranked by actual empty weight — not marketing copy.",
    chip: "Buying guide",
    chipColor: "sun",
    img: "/images/guides/best-lightweight-carry-on-luggage.jpg",
    updated: "September 2026",
  },
  {
    href: "/guides/avoid-checked-baggage-fees",
    title: "How to avoid checked baggage fees",
    blurb: "Credit cards, elite status and packing choices, ranked by how much they actually save.",
    chip: "Money-saving",
    chipColor: "sky",
    img: "/images/guides/avoid-checked-baggage-fees.jpg",
    updated: "September 2026",
  },
  {
    href: "/guides/lufthansa-baggage-rules",
    title: "Lufthansa baggage rules, by fare class",
    blurb: "The cabin bag is fixed at 8 kg — the checked bag depends entirely on your fare.",
    chip: "Airline guide",
    chipColor: "coral",
    img: "/images/guides/lufthansa-baggage-rules.jpg",
    updated: "September 2026",
  },
  {
    href: "/guides/emirates-baggage-rules",
    title: "Emirates baggage rules, explained",
    blurb: "Piece-based or weight-based checked baggage — it depends entirely on your route.",
    chip: "Airline guide",
    chipColor: "sky",
    img: "/images/guides/emirates-baggage-rules.jpg",
    updated: "September 2026",
  },
  {
    href: "/guides/carry-on-vs-personal-item",
    title: "Carry-on vs personal item, what's the difference",
    blurb: "We compared the free personal-item size across our own dataset — it varies by over 50%.",
    chip: "Explainer",
    chipColor: "sun",
    img: "/images/guides/carry-on-vs-personal-item.jpg",
    updated: "September 2026",
  },
  {
    href: "/guides/best-luggage-for-business-travel",
    title: "Best luggage for business travel",
    blurb: "Laptop access, garment protection and a weight budget that survives Lufthansa or Emirates.",
    chip: "Buying guide",
    chipColor: "coral",
    img: "/images/guides/best-luggage-for-business-travel.jpg",
    updated: "September 2026",
  },
  {
    href: "/guides/british-airways-baggage-allowance",
    title: "British Airways baggage allowance, by fare",
    blurb: "Checked bags scale from zero to three depending on cabin and fare — here's the full breakdown.",
    chip: "Airline guide",
    chipColor: "sky",
    img: "/images/guides/british-airways-baggage-allowance.jpg",
    updated: "September 2026",
  },
  {
    href: "/guides/what-not-to-pack-in-carry-on",
    title: "What not to pack in your carry-on",
    blurb: "Liquids, sharp objects, sporting goods, and the one item that must go in the cabin, not checked.",
    chip: "Explainer",
    chipColor: "coral",
    img: "/images/guides/what-not-to-pack-in-carry-on.jpg",
    updated: "September 2026",
  },
  {
    href: "/guides/best-luggage-for-family-travel",
    title: "Best luggage for family travel",
    blurb: "Hard-shell durability, wheel quality, and why a 3-piece set beats one bag per traveler.",
    chip: "Buying guide",
    chipColor: "sun",
    img: "/images/guides/best-luggage-for-family-travel.jpg",
    updated: "September 2026",
  },
  {
    href: "/guides/wizz-air-baggage-rules",
    title: "Wizz Air baggage rules, explained",
    blurb: "One free personal item, a paid Priority cabin bag, and four checked-bag weight tiers.",
    chip: "Airline guide",
    chipColor: "sky",
    img: "/images/guides/wizz-air-baggage-rules.jpg",
    updated: "September 2026",
  },
  {
    href: "/guides/qantas-baggage-allowance",
    title: "Qantas baggage allowance, explained",
    blurb: "Weight-based on some routes, piece-based on others -- here's which applies to you.",
    chip: "Airline guide",
    chipColor: "coral",
    img: "/images/guides/qantas-baggage-allowance.jpg",
    updated: "September 2026",
  },
  {
    href: "/guides/turkish-airlines-baggage-allowance",
    title: "Turkish Airlines baggage allowance",
    blurb: "Your checked allowance depends on the KG or PC concept -- and it's printed on your ticket.",
    chip: "Airline guide",
    chipColor: "sun",
    img: "/images/guides/turkish-airlines-baggage-allowance.jpg",
    updated: "September 2026",
  },
  {
    href: "/guides/icelandair-baggage-allowance",
    title: "Icelandair baggage allowance",
    blurb: "The cheapest fare includes zero checked bags -- and stopover fees apply per leg, not per trip.",
    chip: "Airline guide",
    chipColor: "sky",
    img: "/images/guides/icelandair-baggage-allowance.jpg",
    updated: "September 2026",
  },
  {
    href: "/guides/delta-baggage-allowance",
    title: "Delta baggage allowance and fees",
    blurb: "No cabin-bag weight limit, but checked fees swing hard between Basic Economy and Main Cabin.",
    chip: "Airline guide",
    chipColor: "coral",
    img: "/images/guides/delta-baggage-allowance.jpg",
    updated: "September 2026",
  },
  {
    href: "/guides/united-airlines-baggage-allowance",
    title: "United Airlines baggage allowance",
    blurb: "Fare class sets the checked-bag fee -- but elite status and some credit cards can waive it.",
    chip: "Airline guide",
    chipColor: "sun",
    img: "/images/guides/united-airlines-baggage-allowance.jpg",
    updated: "September 2026",
  },
  {
    href: "/guides/air-canada-baggage-allowance",
    title: "Air Canada baggage allowance",
    blurb: "The cheapest fare shrinks your carry-on too, not just checked bags, on Canada-U.S. routes.",
    chip: "Airline guide",
    chipColor: "sky",
    img: "/images/guides/air-canada-baggage-allowance.jpg",
    updated: "September 2026",
  },
  {
    href: "/guides/singapore-airlines-baggage-allowance",
    title: "Singapore Airlines baggage allowance",
    blurb: "Even the cheapest fare includes a checked bag -- rare among full-service carriers today.",
    chip: "Airline guide",
    chipColor: "coral",
    img: "/images/guides/singapore-airlines-baggage-allowance.jpg",
    updated: "September 2026",
  },
  {
    href: "/guides/easyjet-baggage-allowance",
    title: "easyJet baggage allowance",
    blurb: "The free bag is smaller than you think, and a gate mistake costs a flat GBP 50.",
    chip: "Airline guide",
    chipColor: "sun",
    img: "/images/guides/easyjet-baggage-allowance.jpg",
    updated: "September 2026",
  },
  {
    href: "/guides/american-airlines-baggage-allowance",
    title: "American Airlines baggage allowance",
    blurb: "Basic Economy still includes a full carry-on -- the one thing several rivals don't offer.",
    chip: "Airline guide",
    chipColor: "sky",
    img: "/images/guides/american-airlines-baggage-allowance.jpg",
    updated: "September 2026",
  },
  {
    href: "/guides/jetblue-baggage-allowance",
    title: "JetBlue baggage allowance",
    blurb: "The same Blue Basic fare charges for a first bag at home and gives one away free to Europe.",
    chip: "Airline guide",
    chipColor: "coral",
    img: "/images/guides/jetblue-baggage-allowance.jpg",
    updated: "September 2026",
  },
  {
    href: "/guides/alaska-airlines-baggage-allowance",
    title: "Alaska Airlines baggage allowance",
    blurb: "Same price online or at the airport, plus a 20-minute bag guarantee most US carriers don't match.",
    chip: "Airline guide",
    chipColor: "sun",
    img: "/images/guides/alaska-airlines-baggage-allowance.jpg",
    updated: "September 2026",
  },
  {
    href: "/guides/air-france-baggage-allowance",
    title: "Air France baggage allowance",
    blurb: "Economy Light means zero checked bags -- but status bonuses carry over from sister airline KLM.",
    chip: "Airline guide",
    chipColor: "sky",
    img: "/images/guides/air-france-baggage-allowance.jpg",
    updated: "September 2026",
  },
  {
    href: "/guides/sas-baggage-allowance",
    title: "SAS baggage allowance",
    blurb: "Economy Light means something different depending on where you're flying -- and a 2026 update now gives Silver members a free bag.",
    chip: "Airline guide",
    chipColor: "coral",
    img: "/images/guides/sas-baggage-allowance.jpg",
    updated: "September 2026",
  },
  {
    href: "/guides/swiss-baggage-allowance",
    title: "Swiss baggage allowance",
    blurb: "Light means hand-luggage-only everywhere Swiss flies, and the 32kg weight cap has no pay-your-way-out option.",
    chip: "Airline guide",
    chipColor: "sun",
    img: "/images/guides/swiss-baggage-allowance.jpg",
    updated: "September 2026",
  },
  {
    href: "/guides/finnair-baggage-allowance",
    title: "Finnair baggage allowance",
    blurb: "How many bags you get depends more on the route than the fare -- Asia flights can beat Europe by two full bags.",
    chip: "Airline guide",
    chipColor: "sky",
    img: "/images/guides/finnair-baggage-allowance.jpg",
    updated: "September 2026",
  },
  {
    href: "/guides/klm-baggage-allowance",
    title: "KLM baggage allowance",
    blurb: "Despite the name, Economy Basic doesn't even include a full-size carry-on -- just an under-seat bag.",
    chip: "Airline guide",
    chipColor: "coral",
    img: "/images/guides/klm-baggage-allowance.jpg",
    updated: "September 2026",
  },
  {
    href: "/guides/qatar-airways-baggage-allowance",
    title: "Qatar Airways baggage allowance",
    blurb: "The one airline in our checker that a standard 55x35x20 carry-on doesn't clear.",
    chip: "Airline guide",
    chipColor: "sun",
    img: "/images/guides/qatar-airways-baggage-allowance.jpg",
    updated: "September 2026",
  },
  {
    href: "/guides/etihad-airways-baggage-allowance",
    title: "Etihad Airways baggage allowance",
    blurb: "Basic Economy includes zero checked bags -- and even elite status doesn't rescue it.",
    chip: "Airline guide",
    chipColor: "sky",
    img: "/images/guides/etihad-airways-baggage-allowance.jpg",
    updated: "September 2026",
  },
  {
    href: "/guides/cathay-pacific-baggage-allowance",
    title: "Cathay Pacific baggage allowance",
    blurb: "One of the few airlines where your cabin bag's weight limit rises with your cabin class.",
    chip: "Airline guide",
    chipColor: "coral",
    img: "/images/guides/cathay-pacific-baggage-allowance.jpg",
    updated: "September 2026",
  },
  {
    href: "/guides/norwegian-baggage-allowance",
    title: "Norwegian baggage allowance",
    blurb: "The cheapest fare is personal-item-only -- even on Norwegian's longer routes.",
    chip: "Airline guide",
    chipColor: "sun",
    img: "/images/guides/norwegian-baggage-allowance.jpg",
    updated: "September 2026",
  },
  {
    href: "/guides/aer-lingus-baggage-allowance",
    title: "Aer Lingus baggage allowance",
    blurb: "The personal item is always free -- the 10kg cabin bag depends entirely on your fare.",
    chip: "Airline guide",
    chipColor: "sky",
    img: "/images/guides/aer-lingus-baggage-allowance.jpg",
    updated: "September 2026",
  },
  {
    href: "/guides/japan-airlines-baggage-allowance",
    title: "Japan Airlines baggage allowance",
    blurb: "A generous international allowance that resets to a smaller one on a connecting domestic leg.",
    chip: "Airline guide",
    chipColor: "coral",
    img: "/images/guides/japan-airlines-baggage-allowance.jpg",
    updated: "September 2026",
  },
  {
    href: "/guides/ana-baggage-allowance",
    title: "ANA baggage allowance",
    blurb: "Domestic Japan flights switch to a more generous system on May 19, 2026.",
    chip: "Airline guide",
    chipColor: "sun",
    img: "/images/guides/ana-baggage-allowance.jpg",
    updated: "September 2026",
  },
  {
    href: "/guides/jet2-baggage-allowance",
    title: "Jet2 baggage allowance",
    blurb: "No personal-item-only fare like Ryanair or easyJet -- every ticket includes a 10kg cabin bag.",
    chip: "Airline guide",
    chipColor: "sky",
    img: "/images/guides/jet2-baggage-allowance.jpg",
    updated: "September 2026",
  },
  {
    href: "/guides/westjet-baggage-allowance",
    title: "WestJet baggage allowance",
    blurb: "UltraBasic strips out the full carry-on itself, not just the checked bag, on North American routes.",
    chip: "Airline guide",
    chipColor: "coral",
    img: "/images/guides/westjet-baggage-allowance.jpg",
    updated: "September 2026",
  },
  {
    href: "/guides/tap-air-portugal-baggage-allowance",
    title: "TAP Air Portugal baggage allowance",
    blurb: "Even basic Star Alliance Gold status rescues the otherwise bagless Discount fare.",
    chip: "Airline guide",
    chipColor: "sun",
    img: "/images/guides/tap-air-portugal-baggage-allowance.jpg",
    updated: "September 2026",
  },
  {
    href: "/guides/iberia-baggage-allowance",
    title: "Iberia baggage allowance",
    blurb: "Economy Basic is the one fare tier that skips a complimentary checked bag entirely.",
    chip: "Airline guide",
    chipColor: "sky",
    img: "/images/guides/iberia-baggage-allowance.jpg",
    updated: "September 2026",
  },
  {
    href: "/guides/korean-air-baggage-allowance",
    title: "Korean Air baggage allowance",
    blurb: "A 2025 policy change quietly cut Economy Saver's free bag count to the US from two down to one.",
    chip: "Airline guide",
    chipColor: "coral",
    img: "/images/guides/korean-air-baggage-allowance.jpg",
    updated: "September 2026",
  },
  {
    href: "/guides/thai-airways-baggage-allowance",
    title: "Thai Airways baggage allowance",
    blurb: "A March 2026 switch to a piece-based system means bag count now matters more than total weight.",
    chip: "Airline guide",
    chipColor: "sun",
    img: "/images/guides/thai-airways-baggage-allowance.jpg",
    updated: "September 2026",
  },
  {
    href: "/guides/air-india-baggage-allowance",
    title: "Air India baggage allowance",
    blurb: "An 8kg Economy cabin bag limit -- tighter than most -- and two totally different systems by route.",
    chip: "Airline guide",
    chipColor: "sky",
    img: "/images/guides/air-india-baggage-allowance.jpg",
    updated: "September 2026",
  },
  {
    href: "/guides/air-new-zealand-baggage-allowance",
    title: "Air New Zealand baggage allowance",
    blurb: "The domestic Seat fare is carry-on only -- a trap after a long-haul flight that included checked bags.",
    chip: "Airline guide",
    chipColor: "coral",
    img: "/images/guides/air-new-zealand-baggage-allowance.jpg",
    updated: "September 2026",
  },
  {
    href: "/guides/virgin-australia-baggage-allowance",
    title: "Virgin Australia baggage allowance",
    blurb: "Since February 2026, Economy X gets the same two-bag cabin allowance as Business class.",
    chip: "Airline guide",
    chipColor: "sun",
    img: "/images/guides/virgin-australia-baggage-allowance.jpg",
    updated: "September 2026",
  },
  {
    href: "/guides/austrian-airlines-baggage-allowance",
    title: "Austrian Airlines baggage allowance",
    blurb: "On short and medium-haul routes, Economy Basic skips the cabin bag entirely.",
    chip: "Airline guide",
    chipColor: "sky",
    img: "/images/guides/austrian-airlines-baggage-allowance.jpg",
    updated: "September 2026",
  },
  {
    href: "/guides/brussels-airlines-baggage-allowance",
    title: "Brussels Airlines baggage allowance",
    blurb: "Economy Basic and Light include zero checked bags -- Comfort steps up to one at 23kg.",
    chip: "Airline guide",
    chipColor: "coral",
    img: "/images/guides/brussels-airlines-baggage-allowance.jpg",
    updated: "September 2026",
  },
  {
    href: "/guides/ita-airways-baggage-allowance",
    title: "ITA Airways baggage allowance",
    blurb: "Cabin bags stay capped at 8kg in every class, even Business.",
    chip: "Airline guide",
    chipColor: "sun",
    img: "/images/guides/ita-airways-baggage-allowance.jpg",
    updated: "September 2026",
  },
  {
    href: "/guides/lot-polish-airlines-baggage-allowance",
    title: "LOT Polish Airlines baggage allowance",
    blurb: "The same fare can include one bag or two, depending entirely on the route.",
    chip: "Airline guide",
    chipColor: "sky",
    img: "/images/guides/lot-polish-airlines-baggage-allowance.jpg",
    updated: "September 2026",
  },
  {
    href: "/guides/aegean-airlines-baggage-allowance",
    title: "Aegean Airlines baggage allowance",
    blurb: "Cabin bag size depends on the aircraft type flying your route, not your fare.",
    chip: "Airline guide",
    chipColor: "coral",
    img: "/images/guides/aegean-airlines-baggage-allowance.jpg",
    updated: "September 2026",
  },
  {
    href: "/guides/vueling-baggage-allowance",
    title: "Vueling baggage allowance",
    blurb: "Even the cheapest fare includes a free underseat bag -- the overhead bag is the paid part.",
    chip: "Airline guide",
    chipColor: "sun",
    img: "/images/guides/vueling-baggage-allowance.jpg",
    updated: "September 2026",
  },
  {
    href: "/guides/eurowings-baggage-allowance",
    title: "Eurowings baggage allowance",
    blurb: "BASIC charges extra for a full-size cabin bag that SMART and BIZclass include for free.",
    chip: "Airline guide",
    chipColor: "sky",
    img: "/images/guides/eurowings-baggage-allowance.jpg",
    updated: "September 2026",
  },
  {
    href: "/guides/eva-air-baggage-allowance",
    title: "EVA Air baggage allowance",
    blurb: "Checked baggage switches from one weight-based bag to two pieces on the US-Taiwan route.",
    chip: "Airline guide",
    chipColor: "coral",
    img: "/images/guides/eva-air-baggage-allowance.jpg",
    updated: "September 2026",
  },
  {
    href: "/guides/transavia-baggage-allowance",
    title: "Transavia baggage allowance",
    blurb: "Smart adds a cabin bag but no checked baggage -- Plus does the opposite.",
    chip: "Airline guide",
    chipColor: "sun",
    img: "/images/guides/transavia-baggage-allowance.jpg",
    updated: "September 2026",
  },
  {
    href: "/guides/airbaltic-baggage-allowance",
    title: "airBaltic baggage allowance",
    blurb: "Economy MINI includes a personal item only -- no cabin bag at all.",
    chip: "Airline guide",
    chipColor: "sky",
    img: "/images/guides/airbaltic-baggage-allowance.jpg",
    updated: "September 2026",
  },
  {
    href: "/guides/pegasus-airlines-baggage-allowance",
    title: "Pegasus Airlines baggage allowance",
    blurb: "Light Package means a single 3kg underseat bag -- nothing more.",
    chip: "Airline guide",
    chipColor: "coral",
    img: "/images/guides/pegasus-airlines-baggage-allowance.jpg",
    updated: "September 2026",
  },
  {
    href: "/guides/wideroe-baggage-allowance",
    title: "Wideroe baggage allowance",
    blurb: "Bags over 23kg fly standby on Wideroe's smaller regional aircraft, not guaranteed.",
    chip: "Airline guide",
    chipColor: "sun",
    img: "/images/guides/wideroe-baggage-allowance.jpg",
    updated: "September 2026",
  },
  {
    href: "/guides/norse-atlantic-airways-baggage-allowance",
    title: "Norse Atlantic Airways baggage allowance",
    blurb: "The personal item has officially no weight limit at all -- unusual for a long-haul carrier.",
    chip: "Airline guide",
    chipColor: "sky",
    img: "/images/guides/norse-atlantic-airways-baggage-allowance.jpg",
    updated: "September 2026",
  },
  {
    href: "/guides/china-airlines-baggage-allowance",
    title: "China Airlines baggage allowance",
    blurb: "Economy checked baggage swings from zero to two bags depending on the route.",
    chip: "Airline guide",
    chipColor: "coral",
    img: "/images/guides/china-airlines-baggage-allowance.jpg",
    updated: "September 2026",
  },
  {
    href: "/guides/jetstar-baggage-allowance",
    title: "Jetstar baggage allowance",
    blurb: "Carry-on rules on Jetstar Airways flights are changing from February 2, 2027.",
    chip: "Airline guide",
    chipColor: "sun",
    img: "/images/guides/jetstar-baggage-allowance.jpg",
    updated: "September 2026",
  },
];

export const CHIP_BG: Record<GuideChip, string> = {
  sun: "bg-sun text-ink",
  sky: "bg-sky text-cream",
  coral: "bg-coral text-ink",
};
