import type { MetadataRoute } from "next";
import { SITE } from "@/lib/site";

const routes = [
  "",
  "/guides",
  "/guides/best-carry-on-luggage",
  "/guides/best-checked-luggage",
  "/guides/samsonite-vs-delsey",
  "/guides/ryanair-baggage-rules",
  "/guides/southwest-baggage-policy",
  "/guides/best-lightweight-carry-on-luggage",
  "/guides/avoid-checked-baggage-fees",
  "/guides/lufthansa-baggage-rules",
  "/guides/emirates-baggage-rules",
  "/guides/carry-on-vs-personal-item",
  "/guides/best-luggage-for-business-travel",
  "/guides/british-airways-baggage-allowance",
  "/guides/what-not-to-pack-in-carry-on",
  "/guides/best-luggage-for-family-travel",
  "/guides/wizz-air-baggage-rules",
  "/guides/qantas-baggage-allowance",
  "/guides/turkish-airlines-baggage-allowance",
  "/guides/icelandair-baggage-allowance",
  "/guides/delta-baggage-allowance",
  "/guides/united-airlines-baggage-allowance",
  "/guides/air-canada-baggage-allowance",
  "/guides/singapore-airlines-baggage-allowance",
  "/guides/easyjet-baggage-allowance",
  "/guides/american-airlines-baggage-allowance",
  "/guides/jetblue-baggage-allowance",
  "/guides/alaska-airlines-baggage-allowance",
  "/guides/air-france-baggage-allowance",
  "/guides/sas-baggage-allowance",
  "/guides/swiss-baggage-allowance",
  "/guides/finnair-baggage-allowance",
  "/guides/klm-baggage-allowance",
  "/guides/qatar-airways-baggage-allowance",
  "/guides/etihad-airways-baggage-allowance",
  "/guides/cathay-pacific-baggage-allowance",
  "/guides/norwegian-baggage-allowance",
  "/guides/aer-lingus-baggage-allowance",
  "/guides/japan-airlines-baggage-allowance",
  "/guides/ana-baggage-allowance",
  "/guides/jet2-baggage-allowance",
  "/guides/westjet-baggage-allowance",
  "/guides/tap-air-portugal-baggage-allowance",
  "/guides/iberia-baggage-allowance",
  "/guides/korean-air-baggage-allowance",
  "/guides/thai-airways-baggage-allowance",
  "/guides/air-india-baggage-allowance",
  "/guides/air-new-zealand-baggage-allowance",
  "/guides/virgin-australia-baggage-allowance",
  "/guides/austrian-airlines-baggage-allowance",
  "/guides/brussels-airlines-baggage-allowance",
  "/guides/ita-airways-baggage-allowance",
  "/guides/lot-polish-airlines-baggage-allowance",
  "/guides/aegean-airlines-baggage-allowance",
  "/guides/vueling-baggage-allowance",
  "/guides/eurowings-baggage-allowance",
  "/guides/eva-air-baggage-allowance",
  "/guides/transavia-baggage-allowance",
  "/guides/airbaltic-baggage-allowance",
  "/guides/pegasus-airlines-baggage-allowance",
  "/guides/wideroe-baggage-allowance",
  "/guides/norse-atlantic-airways-baggage-allowance",
  "/guides/china-airlines-baggage-allowance",
  "/guides/jetstar-baggage-allowance",
  "/tools/carry-on-checker",
  "/tools/packing-list",
  "/glossary",
  "/about",
  "/affiliate-disclosure",
  "/privacy-policy",
];

export default function sitemap(): MetadataRoute.Sitemap {
  return routes.map((route) => ({
    url: `${SITE.url}${route}`,
    lastModified: new Date(),
    changeFrequency: route === "" ? "weekly" : "monthly",
    priority: route === "" ? 1 : 0.7,
  }));
}
